### ISSUE TITLE
TT-RSS?

### ISSUE THREAD

**Issue by alphapapa** [fasheng/elfeed-protocol#1]
Hi there,

This looks like a very interesting and well-written project!  I'm curious, I see you mentioned TT-RSS in the readme as a to-do.  Does this mean that you're planning on supporting it yourself, or that you're hoping someone will send a PR for it?  :)

Thanks.

**Comment by fasheng** [comment]
Glade to see someone interested in the project. If you don't mind, I plan to implement TTRSS this weekend. And of course any PR is welcome, too :)

**Comment by alphapapa** [comment]
Thanks.  I have a TT-RSS installation setup but I haven't been using it very regularly.  It would be great to be able to use the same system from Emacs and in the TT-RSS Android app.  I have some other projects going on so I will be an observer for this one.  :)  But I may be able to help test when you have it ready for that.

**Comment by fasheng** [comment]
Most work finished, but still need some time to debug errors, and the body need a sleep now ;)

**Comment by alphapapa** [comment]
You earned it!  :)  I will try to test soon.

**Comment by fasheng** [comment]
After another hours work today, the code finished finally :)

TT-RSS API just looks not like owncloud News, it defined both view mode and feed ID which I'm not very understand. And there is no clear method to fetch articles that modified since last time, so if unread/starred/published states changed in another clients, the other clients like elfeed-protocol could not catch them easily. So I just update all articles with the offset ID, this at least could ensure all articles will be fetched to elfeed instead of the only unread ones. You know some people just can't stand something missed xD

And I deployed a ttrss docker service in local and tested for several times, so it should works. You could help to test it in free time and wait for your report :)

BTW: I really like your packages like `helm-org-rifle`, thanks for the great work and will study the code later :+1:

**Comment by alphapapa** [comment]
Thanks, I will check it out!

> BTW: I really like your packages like helm-org-rifle, thanks for the great work and will study the code later

Thanks for your kind words.  I hope you find them useful.  Please let me know if you have any suggestions.
