### ISSUE TITLE
.authinfo

### ISSUE THREAD

**Issue by justexercises** [fasheng/elfeed-protocol#10]
Hello,

It is posible to use .authinfo file to autenticate? I don't like leave plain passwords in my .emacs file. 
Thanks for this good piece of software!

**Comment by fasheng** [comment]
Thanks your advice, I will try to implemented it later.

**Comment by fasheng** [comment]
Finished, please have a try with format 4 in README~
```lisp
                    ;; format 4, for password in .authinfo, ensure (auth-source-search :host "myhost.com" :port "443" :user "user4") exists
                    (list "owncloud+https://user4@myhost.com"
                          :use-authinfo t)
```

**Comment by justexercises** [comment]
It woks absolutely fine, thanks a lot!

**Comment by gigavinyl** [comment]
Will this work with newsblur as well? Could I see an example?

**Comment by fasheng** [comment]
@gigavinyl  For newsblur, the content of `~/.authinfo` just looks like:
```
machine newsblur.com port 443 login <your-username> password <your-password>
```

and here is the related elfeed-protocol configuration:
```lisp
(list "newsblur+https://<your-username>@newsblur.com"
       :use-authinfo t)
```

Generally, just ensure emacs could get the password with `auth-source-search` and everything will be fine:
```lisp
(auth-source-search :host "newsblur.com" :port "443" :user " <your-username>")
```

Besides, you could use `~/.authinfo.gpg` instead of `~/.authinfo` for security case.

Enjoy!
