### ISSUE TITLE
TTRSS tags not fetched

### ISSUE THREAD

**Issue by rgemulla** [fasheng/elfeed-protocol#36]
When fetching entries from TTRSS, tags other than unread are not fetched anymore. I did set `elfeed-protocol-ttrss-fetch-tags` to `t`, but that does not appear to have any effect.

I use Emacs 27, the latest version of elfeed-protocol, and TTRSS 20.05.

**Comment by fasheng** [comment]
Yes, for we use `getArticle` instead of `getHeadlines` to fetch entries, and `getArticle`
do not provide tags item any more. So this variable only works when fetching
entries in first time.

So I change the default value to `nil` after that, and maybe should remove it later.

https://github.com/fasheng/elfeed-protocol/blob/master/elfeed-protocol-ttrss.el#L45

**Comment by rgemulla** [comment]
For me, even articles fetched for the first time do not show tags anymore (I tried starting from an empty elfeed db).

**Comment by fasheng** [comment]
Well, it should work when initialize a ttrss db, maybe you forget set it to `t`.
We use `getArticle` instead of `getHeadlines` because it could fetch the older articles one by one.
Anyway, I decided to remove the variable so as not to cause more ambiguity.

**Comment by rgemulla** [comment]
Ok. So tags are now unsupported? If so, what would it take to get them back in?

**Comment by fasheng** [comment]
Once ttrss api provide tags information to `getArticle`, I will add it back again. And I personally use `elfeed-org` instead.
