### ISSUE TITLE
feeds imported from elfeed to nextcloud

### ISSUE THREAD

**Issue by divansantana** [fasheng/elfeed-protocol#55]
This is a impressive project and all is working well.

This is more of a question.

I'm using your project with nextcloud 22 and elfeed-org.

If I define a list of my rss feeds via something like this:

```
      (setq rmh-elfeed-org-files '("~/myfeeds.org")))
``` 

Would the list of rss/atom feeds be sync'ed to the nextcloud server?

Otherwise, how should one manage this?

**Comment by fasheng** [comment]
Well, I use elfeed-org, too. However there is no good idea to manage and sync feeds between elfeed-org with other RSS services as yet. Maybe because of different RSS services manage feeds with different methods, for example some support folders, and some only support tags.

You have to export/sync feeds to file and import it to your RSS service manually.

Another choice is mange feeds in RSS service, and fetch the folder/category as elfeed's tag, TTRSS support such feature until now:
https://github.com/fasheng/elfeed-protocol/pull/46

**Comment by divansantana** [comment]
Great, thanks for the feedback. 

No problem.  Let me export the feed and import it into nextcloud for now.

**Comment by divansantana** [comment]
And to avoid duplicate rss feeds in elfeed?  Do you export your .org file to opml and then configure elfeed to only read the rss feeds from the protocol provider and not from the org file?

**Comment by fasheng** [comment]
Yes, I mange my feeds with elfeed-org, and export them to opml that the RSS service support manually(the opml format will be a little different for RSS services).

And, I use elfeed-org to manage the feed tags, it's optional but works great. Apart from this, elfeed-protocol will not read feeds from elfeed-org, it always fetch latest feeds from RSS service.

**Comment by divansantana** [comment]
ok got it, thanks. :)
